import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Layout = ({ children }) => {
    return (
        <div className={styles.container}>
      <Head>
        <title>Super Heros App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        { children }
      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
    )
}

export default Layout
